## Parameters

load:
  data_path_train: ExperimentsDVC/dataset/jan_train.csv
  data_path_test: ExperimentsDVC/dataset/jan_test.csv

featureselection:
  data: ExperimentsDVC/data/raw/jan_train.csv
  features:
  - id
  - sat_id
  - x_sim
  - y_sim
  - z_sim
  - Vx_sim
  - Vy_sim
  - Vz_sim
  - Day
  - Hour
  - Minute
  labels:
  - x
  - y
  - z
  - Vx
  - Vy
  - Vz
splitdata:
  size: 0.33
  state: 42

standardscaler:
  data:

train:
  n_estimators: 150
  max_samples: 20000
  max_depth: 20
  min_samples_split: 10
  min_impurity_decrease: 0.2



