

## Parameters

load:
  data_path_train: ExperimentsDVC/data/raw/jan_train.csv

featureselection:
  data: ExperimentsDVC/data/raw/jan_train.csv
  features:
    - id
    - sat_id
    - x_sim
    - y_sim
    - z_sim
    - Vx_sim
    - Vy_sim
    - Vz_sim
  labels:
    - x
    - y
    - z 
    - Vx
    - Vy
    - Vz
splitdata:
  size: 0.33
  state: 42

standardscaler:
  data:

train:
  data:
  parameters:
    - n_estimators: 100
    - max_depth: 50
    - min_samples_split: 10
    - min_impurity_decrease: 1



